name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "0 4 * * 3"
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
  
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_DEPLOY_KEY }}
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2
    - name: Build
      id: build
      env:
        DOCKER_USER: ${{ secrets.DOCKER_HUB_USERNAME }}
        DOCKER_PLATFORM: ${{ matrix.platform }}
        DISTRIBUTION: ${{ matrix.distribution }}
        BUILD_NR: ${{ github.run_number }}
      run: |
        docker buildx build \
          --tag "${DOCKER_USER}/node-red-hass:latest","${DOCKER_USER}/node-red-hass:$(date -I)" \
          --platform=linux/amd64,linux/arm64,linux/arm/v7 \
          --push \
          -f Dockerfile .

